language: node_js
node_js:
  - "6"

before_install:
  - git config --global push.default matching
  - git config --global user.name "zack9433"
  - git config --global user.email "zack9433@gmail.com"
  - sed -i'' "/^ *repo/s~github\.com~${DEPLOY_REPO}@github.com~" _config.yml

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo d -g --silent

cache:
  directories:
    - node_modules
