# basic
title: RD 日常
subtitle: Code, Life, Coffee, That's it.
description: 紀錄 RD 日常的 murmur
favicon: favicon.ico
avatar: images/avatar.jpg

# disqus
disqus_shortname: drakeleung

# social
social:
  github: https://github.com/zack9433
  twitter: https://twitter.com/zack9433
  linkedin: https://www.linkedin.com/in/zayang
  facebook: https://facebook.com/zack9433

# nav #
nav:
  home: .
  archive: archives
  about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
